[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

[[bin]]
name="thread"
path="src/thread.rs"

[[bin]]
name="safe_list"
path="src/safe_list.rs"

[[bin]]
name="rwlock"
path="src/rwlock.rs"


[[bin]]
name="mutex"
path="src/mutex.rs"
