[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sqlparser = "0.41.0"
# rustyline = "9"
# env_logger = "0.11.0"
parquet = "46.0.0"
parquet_derive = "46.0.0"